### ISSUE TITLE
About the operation of obtaining pictures for a period of time

### ISSUE THREAD

**Issue by YIN-Renlong** [berkerol/photo-of-the-day#5]
First of all, thanks for this project. I would like to ask that is it possible to obtain a period of time (instead of just one picture)? For example, by using the command `$ potd -N -d 2019-05-06 2019-06-06` to obtain all NG pictures from May 6, 2019 to June 6, 2019.

Can you please let me know if it is possible technically?

Thanks.

**Comment by berkerol** [comment]
Thanks for your interest. Since this tool is designed for setting wallpapers, it is not possible to download in bulks natively. However, you can write a small script that loops through the specified period and then for each date you can call this tool for downloading. For that purpose, I can add an additional argument that will skip the wallpaper setting section so that your script can run a bit faster.

**Comment by YIN-Renlong** [comment]
> Thanks for your interest. Since this tool is designed for setting wallpapers, it is not possible to download in bulks natively. However, you can write a small script that loops through the specified period and then for each date you can call this tool for downloading. For that purpose, I can add an additional argument that will skip the wallpaper setting section so that your script can run a bit faster.

Hi, thank you for your reply. Unfortunately I haven't tried javascript yet, it would be hard for me to complete this further function. I kindly ask that If you can help implement this feature? I would be much grateful for that. Best

**Comment by berkerol** [comment]
You can use the additional argument in the latest commit to skip the wallpaper setting section.

**Comment by YIN-Renlong** [comment]
> You can use the additional argument in the latest commit to skip the wallpaper setting section.

Thanks!
